apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: new-nfs-provisioner-utility
  name: new-datadir-postgres-guacamole-0-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  nfs:
    path: /AG-Ritter-VRE-Utility-namespace/vre-project-indoctestproject-datadir-postgres-guacamole-0-pvc-0362ce0f-9c62-486b-bf6c-7ff806431536
    server: bihnas2.charite.de
  persistentVolumeReclaimPolicy: Retain
  storageClassName: new-managed-nfs-storage-utility
  volumeMode: Filesystem
