apiVersion: v1
kind: Service
metadata:
  name: message-bus-greenroom
  namespace: greenroom
  labels:
    app: message-bus-greenroom
spec:
  ports:
  - port: 15672
    protocol: TCP
    targetPort: 15672
    name: "15672"
    nodePort:
  - port: 5672
    targetPort: 5672
    protocol: TCP
    name: "5672"
    nodePort:
  selector:
    app: message-bus-greenroom
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-bus-greenroom
  namespace: greenroom
  labels:
    app: message-bus-greenroom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-bus-greenroom
  template:
    metadata:
      labels:
        app: message-bus-greenroom
    spec:
      containers:
      - name: rabbitmq
        image: s-hdp-vre-v007.charite.de/rabbitmq:3-management
        ports:
        - containerPort: 4369
        - containerPort: 5671
        - containerPort: 5672
        - containerPort: 15671
        - containerPort: 15672
        - containerPort: 25672
        env:
        - name: env
          value: "charite"
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: username
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: password
        resources:
          requests:
            memory: "1000Mi"
            cpu: "1"
          limits:
            memory: "1000Mi"
            cpu: "1"
      nodeSelector:
        namespace: greenroom
