apiVersion: v1
kind: Service
metadata:
  name: neo4j-db
  namespace: utility
  labels:
    app: neo4j-db
spec:
  ports:
    - name: http
      port: 7474
      targetPort: 7474
      nodePort:
    - name: bolt
      port: 7687
      targetPort: 7687
      nodePort:
  selector:
    app: neo4j-db
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j-db
  namespace: utility
spec:
  serviceName: neo4j-db
  replicas: 1
  selector:
    matchLabels:
      app: neo4j-db
  template:
    metadata:
      labels:
        app: neo4j-db
    spec:
      containers:
      - name: neo4j
        image: s-hdp-vre-v007.charite.de/neo4j:4.0
        env:
          - name: NEO4J_apoc_export_file_enabled
            value: "true"
          - name: NEO4J_apoc_import_file_enabled
            value: "true"
          - name: NEO4J_apoc_import_file_use__neo4j__config
            value: "true"
          - name: NEO4JLABS_PLUGINS
            value: \[\"apoc\"\]
          - name: env
            value: "charite"
#          - name: NEO4J_SECRETS_PASSWORD
#            valueFrom:
#              secretKeyRef:
#                name: neo4j-password
#                key: neo4j-password
        ports:
        - containerPort: 7474
          name: browser
        - containerPort: 7687
          name: bolt
        volumeMounts:
        - name: neo4j-data
          mountPath: /data
        - name: neo4j-plugins
          mountPath: /plugins
        - name: neo4j-logs
          mountPath: /logs
        readinessProbe:
          tcpSocket:
            port: 7687
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "16Gi"
            cpu: "4"
          limits:
            memory: "16Gi"
            cpu: "4"
      terminationGracePeriodSeconds: 60
      nodeSelector:
        namespace: utility
  volumeClaimTemplates:
  - metadata:
      name: neo4j-data
      annotations:
        volume.beta.kubernetes.io/storage-class: new-managed-nfs-storage-utility
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
  - metadata:
      name: neo4j-plugins
      annotations:
        volume.beta.kubernetes.io/storage-class: new-managed-nfs-storage-utility
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
  - metadata:
      name: neo4j-logs
      annotations:
        volume.beta.kubernetes.io/storage-class: new-managed-nfs-storage-utility
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 30Gi
