apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: new-nfs-provisioner-utility
  name: new-neo4j-logs-neo4j-db-0-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 30Gi
  nfs:
    path: /AG-Ritter-VRE-Utility-namespace/utility-neo4j-logs-neo4j-db-0-pvc-40cd7534-0420-4538-9f71-62e43115f630
    server: bihnas2.charite.de
  persistentVolumeReclaimPolicy: Retain
  storageClassName: new-managed-nfs-storage-utility
  volumeMode: Filesystem
