apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: new-nfs-provisioner-utility
  name: new-neo4j-plugins-neo4j-db-0
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  nfs:
    path: /AG-Ritter-VRE-Utility-namespace/utility-neo4j-plugins-neo4j-db-0-pvc-3600cab7-a072-4dff-a07a-fd9055b43481
    server: bihnas2.charite.de
  persistentVolumeReclaimPolicy: Retain
  storageClassName: new-managed-nfs-storage-utility
  volumeMode: Filesystem
