apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: new-managed-nfs-storage-utility
    volume.beta.kubernetes.io/storage-provisioner: new-nfs-provisioner-utility
  labels:
    app: neo4j-db-restore
  name: neo4j-plugins-restore-neo4j-db-restore-0
  namespace: utility
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  volumeName: new-neo4j-plugins-restore-neo4j-db-restore-0-pv
