apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: new-nfs-provisioner-utility
  name: new-neo4j-logs-restore-neo4j-db-restore-0-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 30Gi
  nfs:
    path: /AG-Ritter-VRE-Utility-namespace/utility-neo4j-logs-restore-neo4j-db-restore-0-pvc-c76d9ea3-c9b3-4504-98f4-e92dc8281286
    server: bihnas2.charite.de
  persistentVolumeReclaimPolicy: Retain
  storageClassName: new-managed-nfs-storage-utility
  volumeMode: Filesystem
