apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j-data-pv
  namespace: utility
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/neo4j
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j-logs-pv
  namespace: utility
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /logs
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-data-pvc
  namespace: utility
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: neo4j-data-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: neo4j-logs-pv
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j-db
  namespace: utility
  labels:
    app: neo4j-db
spec:
  ports:
    - name: http
      port: 7474
      targetPort: 7474
    - name: bolt
      port: 7687
      targetPort: 7687
  selector:
    app: neo4j-db
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j-db
  namespace: utility
spec:
  serviceName: neo4j-db
  replicas: 1
  selector:
    matchLabels:
      app: neo4j-db
  template:
    metadata:
      labels:
        app: neo4j-db
    spec:
      containers:
      - name: neo4j
        image: ghcr.io/vre-charite/neo4j:4.0.8
        lifecycle:
          postStart:
            exec:
              command:
                - "sh"
                - "-c"
                - |
                  sleep 10 && cypher-shell -u neo4j -p $PASSWORD -f /var/lib/neo4j/scripts/user_admin.cypher --param "ROLE => 'admin'" --param "EMAIL => '$ADMIN_EMAIL'" 

        env:
          - name: NEO4J_apoc_export_file_enabled
            value: "true"
          - name: NEO4J_apoc_import_file_enabled
            value: "true"
          - name: NEO4J_apoc_import_file_use__neo4j__config
            value: "true"
          - name: NEO4JLABS_PLUGINS
            value: \[\"apoc\"\]
          - name: env
            value: "charite"
          - name: NEO4J_AUTH
            value: "neo4j/password"
          - name: NEO4j_dbms_connector_bolt_listen__address
            value: "0.0.0.0:7687"
          - name: USER
            value: "neo4j"
          - name: PASSWORD
            value: "password"
          - name: ADMIN_EMAIL
            value: "test-vre-admin@charite.de"
#          - name: NEO4J_SECRETS_PASSWORD
#            valueFrom:
#              secretKeyRef:
#                name: neo4j-password
#                key: neo4j-password
        ports:
        - containerPort: 7474
          name: browser
        - containerPort: 7687
          name: bolt
        volumeMounts:
        - name: neo4j-data-volume-mounts
          mountPath: /data
        - name: neo4j-logs-volume-mounts
          mountPath: /logs
        - name: script
          mountPath: /var/lib/neo4j/scripts
        #- name: neo4j-plugins
        #  mountPath: /plugins
        readinessProbe:
          tcpSocket:
            port: 7687
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "1"
      terminationGracePeriodSeconds: 60
      volumes:
        - name: neo4j-data-volume-mounts
          persistentVolumeClaim:
            claimName: neo4j-data-pvc
        - name: neo4j-logs-volume-mounts
          persistentVolumeClaim:
            claimName: neo4j-logs-pvc
        - name: script
          configMap:
            name: scripts-configmap
            defaultMode: 0777
  