apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: greenroom
  name: greenroom-vre-storage
  annotations:
    volume.beta.kubernetes.io/storage-class: managed-nfs-storage-vre
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 30Ti
