apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: new-nfs-provisioner-vre
  name: new-greenroom-vre-storage-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 30Ti
  nfs:
    path: /AG-Ritter-VRE-VRE-namespace/greenroom-greenroom-vre-storage-pvc-2ab6c41c-35f7-41e4-9cf9-ff3c2d653b08
    server: bihnas2.charite.de
  persistentVolumeReclaimPolicy: Retain
  storageClassName: new-managed-nfs-storage-vre
  volumeMode: Filesystem
