apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: new-nfs-provisioner-greenroom
  name: new-greenroom-storage-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 50Ti
  nfs:
    path: /AG-Ritter-VRE-Greenroom-namespace/greenroom-greenroom-storage-pvc-3234fc87-3ad3-4882-b786-586db6e86886
    server: bihnas2.charite.de
  persistentVolumeReclaimPolicy: Retain
  storageClassName: new-managed-nfs-storage-greenroom
  volumeMode: Filesystem
