apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: new-nfs-provisioner-vre
  finalizers:
  - kubernetes.io/pv-protection
  name: new-vre-data-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 30Ti
  nfs:
    path: /AG-Ritter-VRE-VRE-namespace/vre-vre-data-pvc-ab20736f-3a07-4f3e-bfc9-5c804e6a34d4
    server: bihnas2.charite.de
  persistentVolumeReclaimPolicy: Retain
  storageClassName: new-managed-nfs-storage-vre
  volumeMode: Filesystem
