apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: vre
  name: vre-data
  annotations:
    volume.beta.kubernetes.io/storage-class: managed-nfs-storage-vre
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 30Ti
