apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opsdb
  namespace: utility
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opsdb
  serviceName: opsdb
  template:
    metadata:
      labels:
        app: opsdb
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: INDOC_VRE
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: KEYCLOAK_USER
          value: keycloak
        - name: KEYCLOAK_PASSWORD
          value: keycloak
        - name: KEYCLOAK_DB
          value: keycloak
        image: postgres:9.5
        name: postgres
        command: ["/bin/sh","-c"]
        args: ["sh /init-keycloak.sh; psql -a -f /opsdbschema.sql -U indoc_vre;  psql -a -f /casbinonly.sql -U indoc_vre "]
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: datadir
          subPath: pgdata
        - name: init-keycloak
          mountPath: /init-keycloak.sh
        - name: opsdbschema
          mountPath: /opsdbschema.sql
        - name: casbinonly
          mountPath: /casbinonly.sql
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "2Gi"
            cpu: "2"
          limits:
            memory: "8Gi"
            cpu: "2"
      terminationGracePeriodSeconds: 60
      volumes:
        - name: init-keycloak
          configMap:
          name: init-keycloak.sh
        - name: opsdbschema
          configMap:
          name: opsdbschema.sql
        - name: casbinonly
          configMap:
          name: casbinonly.sql
  volumeClaimTemplates:
  - metadata:
      name: datadir
      annotations:
        volume.beta.kubernetes.io/storage-class: cinder-csi
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: opsdb
  namespace: utility
  labels:
    app: opsdb
spec:
  ports:
  - name: pgql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: opsdb
  type: ClusterIP
