apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opsdb
  namespace: utility
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opsdb
  serviceName: opsdb
  template:
    metadata:
      labels:
        app: opsdb
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: INDOC_VRE
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: KEYCLOAK_USER
          value: keycloak
        - name: KEYCLOAK_PASSWORD
          value: keycloak
        - name: KEYCLOAK_DB
          value: keycloak
        image: postgres:9.5
        name: postgres
        lifecycle:
            postStart:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - |
                    psql -U postgres -a -f ./script/init_db.sql;
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: opsdb-persistent-storage
          subPath: pgdata
        - name: script
          mountPath: /script
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "2Gi"
            cpu: "2"
          limits:
            memory: "8Gi"
            cpu: "2"
      terminationGracePeriodSeconds: 60
      volumes:
        - name: opsdb-persistent-storage # Obtaining 'volume' from PVC
          persistentVolumeClaim:
            claimName: opsdb-pvc
        - name: script
          configMap:
            name: init-opsdb-configmap
            defaultMode: 0777
  volumeClaimTemplates:
  - metadata:
      name: opsdb
      annotations:
        volume.beta.kubernetes.io/storage-class: cinder-csi
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  name: opsdb
  namespace: utility
  labels:
    app: opsdb
spec:
  ports:
  - name: pgql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: opsdb
  type: ClusterIP
