apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: new-managed-nfs-storage-utility
    volume.beta.kubernetes.io/storage-provisioner: new-nfs-provisioner-utility
  labels:
    app: postgres
  name: datadir-postgres-0
  namespace: utility
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  volumeName: new-datadir-postgres-0-pv
