apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: new-nfs-provisioner-utility
  name: new-datadir-opsdb-0-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  nfs:
    path: /AG-Ritter-VRE-Utility-namespace/utility-datadir-opsdb-0-pvc-b46f1505-187c-4ded-9761-a5c0212f7bac
    server: bihnas2.charite.de
  persistentVolumeReclaimPolicy: Retain
  storageClassName: new-managed-nfs-storage-utility
  volumeMode: Filesystem
