apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: new-nfs-provisioner-utility
  labels:
    app: elasticsearch-master
  name: elasticsearch-master-elasticsearch-master-0
  namespace: utility
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
  storageClassName: new-managed-nfs-storage-utility
  volumeMode: Filesystem
  volumeName: new-elasticsearch-master-elasticsearch-master-0-pv
