apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage-vre
provisioner: nfs-provisioner-vre
parameters:
  archiveOnDelete: "false"
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage-utility
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: nfs-provisioner-utility
parameters:
  archiveOnDelete: "false"
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage-greenroom
provisioner: nfs-provisioner-greenroom
parameters:
  archiveOnDelete: "false"
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage-minio
provisioner: nfs-provisioner-minio
parameters:
  archiveOnDelete: "false"
allowVolumeExpansion: true
