global:
  enabled: true
  tlsDisable: false

server:
  extraEnvironmentVars:
    VAULT_CACERT: /vault/userconfig/vault-server-tls/vault.ca

  extraVolumes:
    - type: secret
      name: vault-server-tls

  affinity: ""

  ha:
    enabled: true
    config: |
      ui = true
      max_lease_ttl = "8784h"
      default_lease_ttl = "8784h"

      listener "tcp" {
        address = "[::]:8200"
        cluster_address = "[::]:8201"
        tls_cert_file = "/vault/userconfig/vault-server-tls/vault.crt"
        tls_key_file  = "/vault/userconfig/vault-server-tls/vault.key"
        tls_client_ca_file = "/vault/userconfig/vault-server-tls/vault.ca"
      }
      storage "consul" {
        path = "vault"
        address = "HOST_IP:8500"
      }

      service_registration "kubernetes" {}

#  service:
#    type: LoadBalancer
  image:
    repository: "s-hdp-vre-v007.charite.de/vault"
    tag: "1.4.2"
    pullPolicy: IfNotPresent
  nodeSelector: |
    namespace: utility

injector:
  enabled: true
  image:
    repository: "s-hdp-vre-v007.charite.de/vault-k8s"
    tag: "0.4.0"
    pullPolicy: IfNotPresent
  nodeSelector: |
    namespace: utility
