apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: utility
  labels:
    app: keycloak
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort:
  selector:
    app: keycloak
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: utility
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: s-hdp-vre-v007.charite.de/keycloak:10.0.2
        env:
        - name: DB_VENDOR
          value: "postgres"
        - name: KEYCLOAK_USER
          value: "admin"
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: KEYCLOAK_PASSWORD
          value: "$PASSWORD"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: keycloak-db
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-db
              key: password
        - name: DB_ADDR
          value: "opsdb.utility"
        - name: DB_PORT
          value: "5432"
        - name: DB_DATABASE
          value: "keycloak"
        - name: JDBC_PARAMS
          value: "verifyServerCertificate=false&useSSL=false"
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: env
          value: "charite"
        - name: JAVA_OPTS
          value: "-Dkeycloak.profile.feature.token_exchange=enabled -Dkeycloak.profile.feature.scripts=enabled -Dkeycloak.profile.feature.upload_scripts=enabled -Dkeycloak.adminUrl=https://vre.charite.de/vre/auth/ -Dkeycloak.frontendUrl=https://vre.charite.de/vre/auth/"
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "4Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "1"
        volumeMounts:
          - name: extensions
            mountPath: /opt/jboss/keycloak/standalone/deployments/
          - name: antd
            mountPath: /opt/jboss/keycloak/themes/keycloak-antd/
          - name: standalone-ha
            mountPath: /opt/jboss/keycloak/standalone/configuration/standalone-ha.xml
            subPath: standalone-ha.xml
          - name: standalone
            mountPath: /opt/jboss/keycloak/standalone/configuration/standalone.xml
            subPath: standalone.xml
          - name: index
            mountPath: /opt/jboss/keycloak/welcome-content/index.html
            subPath: index.html
          - name: messages-en
            mountPath: /opt/jboss/keycloak/themes/base/login/messages/messages_en.properties
            subPath: messages_en.properties
      nodeSelector:
        namespace: utility
      volumes:
        - name: extensions
          persistentVolumeClaim:
            claimName: new-keycloak-auth-extension
        - name: antd
          persistentVolumeClaim:
            claimName: new-keycloak-antd
        - name: standalone-ha
          configMap:
            name: standalone-ha.xml
        - name: standalone
          configMap:
            name: standalone.xml
        - name: index
          configMap:
            name: index.html
        - name: messages-en
          configMap:
            name: messages-en.properties
