apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: new-managed-nfs-storage-utility
    volume.beta.kubernetes.io/storage-provisioner: new-nfs-provisioner-utility
  name: new-keycloak-auth-extension
  namespace: utility
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: new-keycloak-auth-extension-pv
