apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: utility
  name: keycloak-auth-extension
  annotations:
    volume.beta.kubernetes.io/storage-class: cinder-csi
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
