apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: new-managed-nfs-storage-minio
    volume.beta.kubernetes.io/storage-provisioner: new-nfs-provisioner-minio
  labels:
    app: minio
  name: minio-data-4-minio-0
  namespace: minio
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5T
  volumeMode: Filesystem
  volumeName: new-minio-data-4-minio-0-pv
