apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: new-nfs-provisioner-minio
  name: new-minio-data-2-minio-0-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5T
  nfs:
    path: /AG-Ritter-VRE-Minio-namespace/minio-minio-data-2-minio-0-pvc-c10877f5-5cc0-47b8-841a-10dfb61712f6
    server: bihnas2.charite.de
  persistentVolumeReclaimPolicy: Retain
  storageClassName: new-managed-nfs-storage-minio
  volumeMode: Filesystem
