apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: new-nfs-provisioner-minio
  name: new-minio-data-4-minio-0-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5T
  nfs:
    path: /AG-Ritter-VRE-Minio-namespace/minio-minio-data-4-minio-0-pvc-cc11d593-02fc-4ec9-9ff6-593bd3b91053
    server: bihnas2.charite.de
  persistentVolumeReclaimPolicy: Retain
  storageClassName: new-managed-nfs-storage-minio
  volumeMode: Filesystem
