apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: new-nfs-provisioner-minio
  name: new-minio-data-1-minio-0-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5T
  nfs:
    path: /AG-Ritter-VRE-Minio-namespace/minio-minio-data-1-minio-0-pvc-ac74287b-4a81-496f-b123-7b0e49f37caa
    server: bihnas2.charite.de
  persistentVolumeReclaimPolicy: Retain
  storageClassName: new-managed-nfs-storage-minio
  volumeMode: Filesystem
