apiVersion: v1
data:
  health-check.sh: |
    #!/bin/bash
    </dev/tcp/atlas-0.atlas.utility.svc.cluster.local/21000 && </dev/tcp/atlas-0.atlas.utility.svc.cluster.local/2181 && </dev/tcp/atlas-0.atlas.utility.svc.cluster.local/61520 && </dev/tcp/atlas-0.atlas.utility.svc.cluster.local/9838 && </dev/tcp/atlas-0.atlas.utility.svc.cluster.local/61500 && </dev/tcp/atlas-0.atlas.utility.svc.cluster.local/61510 && </dev/tcp/atlas-0.atlas.utility.svc.cluster.local/61530
kind: ConfigMap
metadata:
  name: atlas-health-check
  namespace: utility
