apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: new-nfs-provisioner-utility
  name: new-atlas-data-atlas-0-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 800Gi
  nfs:
    path: /AG-Ritter-VRE-Utility-namespace/utility-atlas-data-atlas-0-pvc-8a5a2a0a-97ee-4e17-a798-f21eb4616b4e
    server: bihnas2.charite.de
  persistentVolumeReclaimPolicy: Retain
  storageClassName: new-managed-nfs-storage-utility
  volumeMode: Filesystem
