apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: atlas
  name: atlas
  namespace: utility
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: atlas
  serviceName: atlas
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: atlas
    spec:
      containers:
      - command:
        - /opt/apache-atlas-$(VERSION)/bin/atlas_start.py
        env:
        - name: LOG4J_FORMAT_MSG_NO_LOOKUPS
          value: "true"
        - name: VERSION
          value: 2.1.0
        - name: env
          value: charite
        #image: s-hdp-vre-v007.charite.de/apache-atlas:2.1.0
        image: registry-gitlab.indocresearch.org/pilot/bff_cli:apache-atlas-2.1.0
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - /root/health-check.sh
          failureThreshold: 5
          initialDelaySeconds: 1200
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: atlas
        ports:
        - containerPort: 21000
          protocol: TCP
        - containerPort: 9838
          protocol: TCP
        - containerPort: 2181
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 21000
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "4"
            memory: 16Gi
          requests:
            cpu: "4"
            memory: 16Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/apache-atlas-2.1.0/data
          name: atlas-data
        - mountPath: /opt/apache-atlas-2.1.0/solr/server/solr/edge_index_shard1_replica_n1/data
          name: atlas-solr-entity-1
        - mountPath: /opt/apache-atlas-2.1.0/solr/server/solr/fulltext_index_shard1_replica_n1/data
          name: atlas-solr-entity-2
        - mountPath: /opt/apache-atlas-2.1.0/solr/server/solr/vertex_index_shard1_replica_n1/data
          name: atlas-solr-entity-3
        - mountPath: /opt/apache-atlas-2.1.0/solr/server/solr/configsets/_default/conf/managed-schema
          name: managed-schema
          subPath: managed-schema
        - mountPath: /opt/apache-atlas-2.1.0/logs
          name: atlas-log
        - mountPath: /root/health-check.sh
          name: health-check
          subPath: health-check.sh
        - mountPath: /opt/apache-atlas-2.1.0/conf/users-credentials.properties
          name: atlas-users-credentials
          subPath: users-credentials.properties
      dnsPolicy: ClusterFirst
#      nodeSelector:
#        namespace: utility
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
      volumes:
      - configMap:
          defaultMode: 493
          items:
          - key: health-check.sh
            path: health-check.sh
          name: atlas-health-check
        name: health-check
      - configMap:
          defaultMode: 420
          items:
          - key: managed-schema
            path: managed-schema
          name: managed-schema
        name: managed-schema
      - configMap:
          defaultMode: 420
          name: users-credentials.properties
        name: atlas-users-credentials
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      annotations:
        volume.beta.kubernetes.io/storage-class: new-managed-nfs-storage-utility
      creationTimestamp: null
      name: atlas-data
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 800Gi
      volumeMode: Filesystem
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      annotations:
        volume.beta.kubernetes.io/storage-class: new-managed-nfs-storage-utility
      creationTimestamp: null
      name: atlas-solr-entity-1
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 10Gi
      volumeMode: Filesystem
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      annotations:
        volume.beta.kubernetes.io/storage-class: new-managed-nfs-storage-utility
      creationTimestamp: null
      name: atlas-solr-entity-2
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 10Gi
      volumeMode: Filesystem
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      annotations:
        volume.beta.kubernetes.io/storage-class: new-managed-nfs-storage-utility
      creationTimestamp: null
      name: atlas-solr-entity-3
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 10Gi
      volumeMode: Filesystem
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      annotations:
        volume.beta.kubernetes.io/storage-class: new-managed-nfs-storage-utility
      creationTimestamp: null
      name: atlas-log
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 30Gi
      volumeMode: Filesystem
