apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: new-nfs-provisioner-utility
  name: new-atlas-solr-entity-3-atlas-0-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  nfs:
    path: /AG-Ritter-VRE-Utility-namespace/utility-atlas-solr-entity-3-atlas-0-pvc-6495a98b-2a0a-4209-abec-cbf0a314c5c6
    server: bihnas2.charite.de
  persistentVolumeReclaimPolicy: Retain
  storageClassName: new-managed-nfs-storage-utility
  volumeMode: Filesystem
