apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: new-nfs-provisioner-utility
  name: new-redis-data-redis-slave-1-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  nfs:
    path: /AG-Ritter-VRE-Utility-namespace/utility-redis-data-redis-slave-1-pvc-6ec07c1b-57b4-4064-82fd-70dcc8cbc595
    server: bihnas2.charite.de
  persistentVolumeReclaimPolicy: Retain
  storageClassName: new-managed-nfs-storage-utility
  volumeMode: Filesystem
