apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: new-nfs-provisioner-utility
  name: new-redis-data-redis-slave-0-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  nfs:
    path: /AG-Ritter-VRE-Utility-namespace/utility-redis-data-redis-slave-0-pvc-98c514c4-fddb-4bc7-b5a8-2915d4ff714c
    server: bihnas2.charite.de
  persistentVolumeReclaimPolicy: Retain
  storageClassName: new-managed-nfs-storage-utility
  volumeMode: Filesystem
